version: "3.9"
services:
  db:
    image:
    container_name: db
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=bike
    volumes:

  server:
    container_name: server
    build:
      context:
      dockerfile:
    ports:
      - "5000:80"
    volumes:

  client:
    container_name: client
    build:
      context:
      dockerfile: Dockerfile
    volumes:
      - ""
    ports:
      - "3000:3000"
    

